version: 0.2
phases:
  build:
    commands:
      - echo "Build phase - packaging Lambda only"
      - zip -j lambda.zip lambda/index.py

artifacts:
  files:
    - cloudformation.yaml
    - lambda.zip
    - website/**/*
    - buildspec-post.yml
